import React, { useEffect, useState } from "react";
import { aiClient } from "../ai/client";
import { MODEL_REGISTRY } from "../ai/capabilities";
import { KeyRound, ShieldCheck, RefreshCw, Trash2 } from "lucide-react";

export const AISettingsModal: React.FC = () => {
  const [key,setKey]=useState(""); const [remember,setRemember]=useState(true); const [testing,setTesting]=useState(false); const [result,setResult]=useState<{ok:boolean;message:string}|null>(null);
  useEffect(()=>{setKey(aiClient.getApiKey()||"");},[]);
  const save=()=>{aiClient.setApiKey(key,remember);setResult({ok:Boolean(key.trim()),message:key.trim()?"API key saved for BYOK mode.":"API key cleared."});};
  const test=async()=>{save();setTesting(true);const r=await aiClient.testConnection();setResult({ok:r.ok,message:`${r.mode}: ${r.message}`});setTesting(false);};
  return <div className="flex-1 bg-slate-950 text-slate-200 p-3 sm:p-6 overflow-y-auto"><div className="max-w-3xl mx-auto space-y-5">
    <div className="border-b border-slate-800 pb-4 flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-amber-500 text-slate-950 flex items-center justify-center"><KeyRound className="w-5 h-5"/></div><div><h2 className="font-bold">AI Connection & BYOK</h2><p className="text-xs text-slate-400">GitHub Pages can run AI in BYOK mode. Secure deployments can set VITE_AI_API_BASE to use a backend proxy.</p></div></div>
    <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-3"><label className="text-xs text-slate-400">Gemini API Key</label><input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="Paste key here..." className="w-full bg-slate-950 border border-slate-800 rounded-lg p-3 text-sm outline-none focus:border-amber-500"/><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)} className="accent-amber-400"/>Remember only in this browser (localStorage). API keys are never stored in project.json or backup ZIP.</label><div className="flex gap-2"><button onClick={save} className="px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-xs font-bold">Save</button><button onClick={test} disabled={testing} className="px-4 py-2 rounded-lg bg-amber-500 hover:bg-amber-400 text-slate-950 text-xs font-bold flex items-center gap-2">{testing&&<RefreshCw className="w-3.5 h-3.5 animate-spin"/>}Test Connection</button><button onClick={()=>{aiClient.clearApiKey();setKey("");setResult({ok:true,message:"API key removed from this browser."});}} className="px-3 py-2 rounded-lg bg-rose-500/10 border border-rose-500/30 text-rose-300 text-xs flex items-center gap-1"><Trash2 className="w-3.5 h-3.5"/>Clear</button></div>{result&&<div className={`text-xs p-3 rounded-lg border ${result.ok?"bg-emerald-500/10 border-emerald-500/20 text-emerald-300":"bg-rose-500/10 border-rose-500/20 text-rose-300"}`}>{result.message}</div>}</div>
    <div className="bg-slate-900 border border-slate-800 rounded-xl p-5"><div className="flex items-center gap-2 text-xs font-bold text-emerald-300 mb-3"><ShieldCheck className="w-4 h-4"/>Verified Capability Registry</div><div className="space-y-2">{Object.entries(MODEL_REGISTRY).map(([id,m])=><div key={id} className="bg-slate-950 border border-slate-800 rounded-lg p-3"><div className="flex justify-between gap-3"><span className="text-xs font-bold">{m.name}</span><code className="text-[10px] text-slate-500">{id}</code></div><p className="text-[10px] text-slate-400 mt-1">{m.provider} • {m.type} • {m.notes||""}</p></div>)}</div></div>
  </div></div>;
};
