import React,{useState}from"react";
import{GoldenTestRunner,GoldenTestResult}from"../tests/goldenTests";
import{ProjectSchema,AssetSchema}from"../types";
import{CheckCircle2,XCircle,Play,RefreshCw,ShieldCheck,FileCheck,MinusCircle}from"lucide-react";

export const GoldenTestModal:React.FC<{project:ProjectSchema;assets:AssetSchema[]}>=({project,assets})=>{const[running,setRunning]=useState(false);const[results,setResults]=useState<GoldenTestResult[]>([]);const run=async()=>{setRunning(true);try{setResults(await GoldenTestRunner.runAllTests({project,assets}));}finally{setRunning(false);}};const pass=results.filter(r=>r.status==="PASS").length,fail=results.filter(r=>r.status==="FAIL").length,skip=results.filter(r=>r.status==="SKIPPED").length;
return <div className="flex-1 bg-slate-950 text-slate-200 p-3 sm:p-6 overflow-y-auto"><div className="max-w-4xl mx-auto space-y-6"><div className="border-b border-slate-800 pb-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-emerald-500 text-slate-950 flex items-center justify-center"><ShieldCheck className="w-5 h-5"/></div><div><h2 className="font-bold">Golden Integration Diagnostics</h2><p className="text-xs text-slate-400">PASS is only shown after a real runtime assertion. Tests needing uploaded fixtures are SKIPPED, never hard-coded PASS.</p></div></div><button onClick={run} disabled={running} className="w-full sm:w-auto py-2.5 px-4 bg-emerald-500 text-slate-950 font-bold text-xs rounded-xl flex gap-2 items-center">{running?<RefreshCw className="w-4 h-4 animate-spin"/>:<Play className="w-4 h-4"/>}Run 8 Diagnostics</button></div>
{results.length>0&&<div className="bg-slate-900 border border-slate-800 rounded-xl p-4 flex justify-between"><span className="text-xs text-slate-400">Runtime summary</span><div className="flex gap-2 text-xs font-mono"><span className="text-emerald-400">PASS {pass}</span><span className="text-rose-400">FAIL {fail}</span><span className="text-amber-400">SKIP {skip}</span></div></div>}
<div className="space-y-3">{results.length===0?<div className="bg-slate-900/60 border border-slate-800 rounded-xl p-8 text-center"><FileCheck className="w-8 h-8 text-slate-600 mx-auto mb-2"/><p className="text-xs text-slate-400">Run diagnostics after uploading representative image/video/document files.</p></div>:results.map(test=><div key={test.id} className="bg-slate-900 border border-slate-800 rounded-xl p-4 space-y-2"><div className="flex justify-between"><div className="flex gap-2 items-center">{test.status==="PASS"?<CheckCircle2 className="w-4 h-4 text-emerald-400"/>:test.status==="SKIPPED"?<MinusCircle className="w-4 h-4 text-amber-400"/>:<XCircle className="w-4 h-4 text-rose-400"/>}<span className="text-xs font-bold">{test.id}: {test.name}</span><span className="text-[10px] bg-slate-950 border border-slate-800 rounded px-2 py-.5">{test.category}</span></div><span className="text-[10px] text-slate-500 font-mono">{test.durationMs}ms</span></div><p className="text-xs text-slate-400 pl-6">{test.details}</p><div className="pl-6 space-y-1">{test.assertions.map((a,i)=><div key={i} className={`text-[11px] flex gap-2 ${a.passed?"text-slate-400":"text-rose-300"}`}><span>{a.passed?"✓":"✗"}</span><span>{a.name}{a.message?`: ${a.message}`:""}</span></div>)}</div></div>)}</div></div></div>};
