// Header Navigation & Ctrl+K AI Command Bar

import React, { useState, useEffect } from "react";
import { ProjectSchema } from "../types";
import { Sparkles, Undo2, Redo2, Download, Palette, Shirt, Package, Layout, FileSpreadsheet, ShieldCheck, Film, Command, KeyRound, WandSparkles, Menu, X } from "lucide-react";

interface HeaderNavProps { project: ProjectSchema; onProjectChange: (p: ProjectSchema) => void; activeView: string; onViewChange: (view: any) => void; canUndo: boolean; canRedo: boolean; onUndo: () => void; onRedo: () => void; onExecuteCommand?: (cmd: string) => void; }
const APP_VERSION = import.meta.env.VITE_APP_VERSION || "1.1.0"; const BUILD_DATE = import.meta.env.VITE_BUILD_DATE || "local"; const COMMIT = (import.meta.env.VITE_COMMIT_SHA || "dev").slice(0, 7);

export const HeaderNav: React.FC<HeaderNavProps> = ({project,onProjectChange,activeView,onViewChange,canUndo,canRedo,onUndo,onRedo,onExecuteCommand}) => {
  const [showCommandBar,setShowCommandBar]=useState(false); const [showMobileNav,setShowMobileNav]=useState(false); const [commandInput,setCommandInput]=useState("");
  useEffect(()=>{const handleKeyDown=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setShowCommandBar(p=>!p);}else if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?onRedo():onUndo();}else if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="y"){e.preventDefault();onRedo();}};window.addEventListener("keydown",handleKeyDown);return()=>window.removeEventListener("keydown",handleKeyDown);},[onUndo,onRedo]);
  const handleCommandSubmit=(e:React.FormEvent)=>{e.preventDefault();if(!commandInput.trim())return;onExecuteCommand?.(commandInput);setCommandInput("");setShowCommandBar(false);};
  const navItems=[{id:"editor",label:"Studio Editor",icon:Film},{id:"video_ai",label:"AI Video",icon:WandSparkles},{id:"fashion",label:"Virtual Try-On",icon:Shirt},{id:"product",label:"Product AI",icon:Package},{id:"templates",label:"Templates & Menu",icon:Layout},{id:"doc_video",label:"Docs to Video",icon:FileSpreadsheet},{id:"brand",label:"Brand Kit",icon:Palette},{id:"ai_settings",label:"AI Settings",icon:KeyRound},{id:"golden_tests",label:"Golden Tests",icon:ShieldCheck},{id:"export",label:"Export",icon:Download}];
  return <><header className="min-h-14 bg-slate-950 border-b border-slate-800 px-2 sm:px-4 py-2 flex items-center justify-between gap-2 text-slate-200 select-none z-30"><div className="flex items-center gap-2 sm:gap-3 min-w-0"><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-amber-500 to-orange-500 flex items-center justify-center font-bold text-slate-950 shadow-md shadow-amber-500/20"><Sparkles className="w-4 h-4"/></div><div className="min-w-0"><span className="text-[10px] sm:text-xs font-black tracking-wide bg-gradient-to-r from-amber-400 to-orange-400 bg-clip-text text-transparent uppercase">HNL CREATIVE AI</span><span className="hidden sm:block text-[9px] font-mono text-slate-500">v{APP_VERSION} • {BUILD_DATE} • {COMMIT}</span></div></div><div className="hidden md:block h-4 w-px bg-slate-800 mx-1"/><input type="text" value={project.name} onChange={(e)=>onProjectChange({...project,name:e.target.value})} className="hidden md:block bg-transparent text-xs font-semibold text-slate-200 px-2 py-1 rounded hover:bg-slate-900 border border-transparent hover:border-slate-800 focus:border-amber-500 focus:bg-slate-900 outline-none transition-all w-36 xl:w-48 truncate"/><div className="hidden sm:flex items-center gap-0.5 bg-slate-900 rounded-lg p-0.5 border border-slate-800"><button onClick={onUndo} disabled={!canUndo} title="Undo (Ctrl+Z)" className="p-1.5 rounded hover:bg-slate-800 text-slate-400 hover:text-slate-200 disabled:opacity-30 transition-colors"><Undo2 className="w-3.5 h-3.5"/></button><button onClick={onRedo} disabled={!canRedo} title="Redo (Ctrl+Y)" className="p-1.5 rounded hover:bg-slate-800 text-slate-400 hover:text-slate-200 disabled:opacity-30 transition-colors"><Redo2 className="w-3.5 h-3.5"/></button></div></div>
    <div className="hidden lg:flex items-center gap-1 bg-slate-900/80 p-1 rounded-xl border border-slate-800 text-xs">{navItems.map(item=>{const Icon=item.icon,isAct=activeView===item.id;return <button key={item.id} onClick={()=>onViewChange(item.id)} className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg font-medium transition-all ${isAct?"bg-amber-500 text-slate-950 font-bold shadow-sm":"text-slate-400 hover:text-slate-200 hover:bg-slate-800/60"}`}><Icon className="w-3.5 h-3.5"/><span>{item.label}</span></button>;})}</div>
    <div className="flex items-center gap-2"><button onClick={()=>setShowMobileNav(true)} className="lg:hidden p-2 rounded-lg border border-slate-800 bg-slate-900 text-slate-300 hover:text-white" aria-label="Open modules" title="Modules"><Menu className="w-4 h-4"/></button><button onClick={()=>setShowCommandBar(true)} className="flex items-center gap-2 bg-slate-900 hover:bg-slate-850 px-3 py-1.5 rounded-lg border border-slate-800 text-xs text-slate-400 hover:text-slate-200 transition-colors"><Command className="w-3.5 h-3.5 text-amber-400"/><span className="hidden sm:inline">AI Command Bar</span><kbd className="hidden sm:inline text-[10px] font-mono bg-slate-950 px-1.5 py-0.5 rounded border border-slate-800 text-slate-500">⌘K</kbd></button></div></header>
    {showMobileNav&&<div className="fixed inset-0 z-50 bg-slate-950/85 backdrop-blur-sm lg:hidden" onClick={()=>setShowMobileNav(false)}><div className="absolute inset-x-0 bottom-0 max-h-[82vh] rounded-t-2xl border-t border-slate-700 bg-slate-900 p-3 shadow-2xl overflow-y-auto" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between px-1 pb-3 border-b border-slate-800"><div><p className="text-xs font-bold text-slate-100">HNL Creative AI modules</p><p className="text-[10px] text-slate-500 truncate max-w-[75vw]">{project.name}</p></div><button onClick={()=>setShowMobileNav(false)} className="p-2 rounded-lg bg-slate-950 border border-slate-800" aria-label="Close modules"><X className="w-4 h-4"/></button></div><div className="grid grid-cols-2 gap-2 pt-3">{navItems.map(item=>{const Icon=item.icon,isAct=activeView===item.id;return <button key={item.id} onClick={()=>{onViewChange(item.id);setShowMobileNav(false);}} className={`min-h-14 p-3 rounded-xl border flex items-center gap-2 text-left ${isAct?"bg-amber-500 text-slate-950 border-amber-400 font-bold":"bg-slate-950 text-slate-300 border-slate-800"}`}><Icon className="w-4 h-4 shrink-0"/><span className="text-[11px] leading-tight">{item.label}</span></button>;})}</div><div className="flex items-center justify-center gap-2 pt-3"><button onClick={onUndo} disabled={!canUndo} className="flex-1 py-2 rounded-lg bg-slate-950 border border-slate-800 text-xs disabled:opacity-30">Undo</button><button onClick={onRedo} disabled={!canRedo} className="flex-1 py-2 rounded-lg bg-slate-950 border border-slate-800 text-xs disabled:opacity-30">Redo</button></div></div></div>}
    {showCommandBar&&<div className="fixed inset-0 bg-slate-950/80 backdrop-blur-sm z-50 flex items-start justify-center pt-14 sm:pt-24 px-3" onClick={()=>setShowCommandBar(false)}><div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-xl shadow-2xl overflow-hidden max-h-[80vh] overflow-y-auto" onClick={e=>e.stopPropagation()}><form onSubmit={handleCommandSubmit} className="p-3 border-b border-slate-800 flex items-center gap-2"><Sparkles className="w-5 h-5 text-amber-400 ml-2"/><input type="text" autoFocus value={commandInput} onChange={e=>setCommandInput(e.target.value)} placeholder="Type an AI command (e.g. 'Cắt 5 giây đầu', 'Đổi sang 9:16', 'Tạo caption tiếng Việt')..." className="w-full bg-transparent text-sm text-slate-100 placeholder:text-slate-500 outline-none p-2"/><button type="submit" className="px-3 py-1.5 bg-amber-500 text-slate-950 text-xs font-bold rounded-lg hover:bg-amber-400">Execute</button></form><div className="p-3 text-xs text-slate-400 space-y-1"><p className="font-semibold text-slate-300">Quick Commands:</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5 pt-1"><button type="button" onClick={()=>{onExecuteCommand?.("Tối ưu hóa nhịp độ timeline và audio ducking");setShowCommandBar(false);}} className="p-2 rounded bg-slate-950 hover:bg-slate-800 text-left border border-slate-800">⚡ Tự động Audio Ducking</button><button type="button" onClick={()=>{onExecuteCommand?.("Đổi khung hình sang 9:16 Shorts");setShowCommandBar(false);}} className="p-2 rounded bg-slate-950 hover:bg-slate-800 text-left border border-slate-800">📱 Chuyển sang 9:16 Shorts</button></div></div></div></div>}
  </>;
};
