import React, { useMemo, useState } from "react";
import { AssetSchema } from "../types";
import { aiClient } from "../ai/client";
import { dataUrlToBlob, probeVideoDuration, urlToDataUrl } from "../utils/media";
import { storage } from "../storage/db";
import { Film, Sparkles, RefreshCw, Video, PlusCircle, AlertCircle } from "lucide-react";

interface Props { assets: AssetSchema[]; onGeneratedAsset: (asset: AssetSchema) => void; }

export const VideoAIStudio: React.FC<Props> = ({assets,onGeneratedAsset}) => {
  const [prompt,setPrompt]=useState("Tạo một cảnh quảng cáo điện ảnh, chuyển động tự nhiên, ánh sáng chuyên nghiệp.");
  const [aspect,setAspect]=useState<"16:9"|"9:16">("16:9"); const [selectedIds,setSelectedIds]=useState<string[]>([]); const [processing,setProcessing]=useState(false); const [videoUrl,setVideoUrl]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
  const refs=useMemo(()=>assets.filter(a=>selectedIds.includes(a.id)&&["image","video"].includes(a.type)),[assets,selectedIds]);
  const toggle=(id:string)=>setSelectedIds(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id].slice(-4));
  const generate=async()=>{setProcessing(true);setError(null);setVideoUrl(null);try{const references=[] as Array<{type:"image"|"video";base64:string;mimeType:string}>;for(const asset of refs){references.push({type:asset.type as "image"|"video",base64:await urlToDataUrl(asset.url),mimeType:asset.mimeType});}const out=await aiClient.generateVideo({prompt,aspectRatio:aspect,references,model:"gemini-omni-flash-preview"});setVideoUrl(out.videoUrl);}catch(e:any){setError(e.message||"Video generation failed");}finally{setProcessing(false);}};
  const add=async()=>{if(!videoUrl)return;const blob=await dataUrlToBlob(videoUrl);const runtime=URL.createObjectURL(blob);const duration=await probeVideoDuration(runtime);const asset:AssetSchema={id:`asset-ai-video-${crypto.randomUUID?.()||Math.random().toString(36).slice(2)}`,name:`AI Video ${new Date().toLocaleTimeString()}`,filename:`ai-video-${Date.now()}.mp4`,type:"video",mimeType:blob.type||"video/mp4",size:blob.size,duration,createdAt:Date.now(),origin:"AI_GENERATED",url:runtime,tags:["video","ai","gemini-omni"],referenceTag:`@aivideo${Date.now().toString().slice(-5)}`};await storage.saveAsset(asset,blob);onGeneratedAsset(asset);};
  const eligible=assets.filter(a=>a.type==="image"||a.type==="video");
  return <div className="flex-1 bg-slate-950 text-slate-200 p-3 sm:p-6 overflow-y-auto"><div className="max-w-5xl mx-auto space-y-5">
    <div className="border-b border-slate-800 pb-4 flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-violet-500 text-white flex items-center justify-center"><Film className="w-5 h-5"/></div><div><h2 className="font-bold">AI Video Studio</h2><p className="text-xs text-slate-400">Text → Video, Image → Video, multiple image references and existing Video → Video through Gemini Omni Flash. Expensive generation only runs after you press Generate.</p></div></div>
    <div className="grid md:grid-cols-[1fr_360px] gap-4"><div className="bg-slate-900 border border-slate-800 rounded-xl p-4 space-y-3"><label className="text-xs font-bold text-violet-300">Prompt</label><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} className="w-full min-h-28 bg-slate-950 border border-slate-800 rounded-lg p-3 text-sm outline-none focus:border-violet-500"/><div className="flex gap-2">{(["16:9","9:16"] as const).map(v=><button key={v} onClick={()=>setAspect(v)} className={`px-3 py-2 text-xs rounded border ${aspect===v?"border-violet-500 bg-violet-500/10":"border-slate-700"}`}>{v}</button>)}</div><button onClick={generate} disabled={processing||!prompt.trim()} className="w-full py-3 rounded-xl bg-violet-500 hover:bg-violet-400 disabled:opacity-50 text-white font-bold text-xs flex items-center justify-center gap-2">{processing?<><RefreshCw className="w-4 h-4 animate-spin"/>Generating video...</>:<><Sparkles className="w-4 h-4"/>Generate with Gemini Omni</>}</button>{error&&<div className="p-3 rounded-lg bg-rose-500/10 border border-rose-500/20 text-xs text-rose-300 flex gap-2"><AlertCircle className="w-4 h-4 shrink-0"/>{error}</div>}</div>
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-4"><div className="text-xs font-bold text-slate-300 mb-2">References ({selectedIds.length}/4)</div><div className="grid grid-cols-2 sm:grid-cols-3 gap-2 max-h-64 overflow-y-auto">{eligible.map(a=><button key={a.id} onClick={()=>toggle(a.id)} className={`h-20 rounded-lg overflow-hidden border relative ${selectedIds.includes(a.id)?"border-violet-500 ring-2 ring-violet-500/20":"border-slate-800"}`}>{a.type==="image"?<img src={a.url} className="w-full h-full object-cover"/>:<div className="w-full h-full flex flex-col items-center justify-center bg-slate-950"><Video className="w-5 h-5 text-sky-400"/><span className="text-[9px] mt-1 truncate max-w-full px-1">{a.name}</span></div>}<span className="absolute top-1 left-1 text-[8px] bg-slate-950/80 px-1 rounded">{a.type}</span></button>)}</div><p className="text-[10px] text-slate-500 mt-3">Select images for style/character/product guidance, or a short existing video for natural-language video editing. Large videos should use a secure backend/File API in production.</p></div></div>
    {videoUrl&&<div className="bg-slate-900 border border-violet-500/30 rounded-xl p-4 space-y-3"><video src={videoUrl} controls className="w-full max-h-[480px] bg-black rounded-lg"/><button onClick={add} className="w-full py-3 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs flex items-center justify-center gap-2"><PlusCircle className="w-4 h-4"/>Save Generated Video to Asset Library & Timeline</button></div>}
  </div></div>;
};
